server:
  port: 10_16

program-agent:
  charts:
    bot-message: true
  client:
    host: "http://localhost:8027/api/"
    myHost: "http://host.docker.internal:1016/api/"
    token: "tuts-token-bot-dev"
    time-delay-send: 15000

telegram:
  bot:
    username: testBot
    token: "1914390526:AAF2pVOEU-ek5yLINFLrcLLjnHB9w4PFZTg"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

bot:
  data_base: testbot


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${bot.data_base}
#    username: postgres
#    password: W12345678
    username: myuser
    password: password12345
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: ru.wdeath.programagent.lib.config.WDSDBDialect
    open-in-view: false
    show-sql: true

